apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: python-sample
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.8'
  output:
    to:
      kind: ImageStreamTag
      name: 'python-sample:latest'
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: 'python:3.8'

